# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0
jobs:
  disabled:
    docker:
      - image:  connyun.azurecr.io/com.connyun/frontend:latest
        auth:
          username: $ACR_USERNAME
          password: $ACR_PASSWORD


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -u${ARTIFACTORY_NPM_USER}:${ARTIFACTORY_NPM_API_KEY} https://connyun.jfrog.io/connyun/api/npm/npm/auth/connyun > .npmrc

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn prod
      # - run: yarn dev-test
      # - run: yarn e2e

  build:
    docker:
      - image:  connyun.azurecr.io/com.connyun/frontend:latest
        auth:
          username: $ACR_USERNAME
          password: $ACR_PASSWORD


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -u${ARTIFACTORY_NPM_USER}:${ARTIFACTORY_NPM_API_KEY} https://connyun.jfrog.io/connyun/api/npm/npm/auth/connyun > .npmrc

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: curl -fL https://getcli.jfrog.io | sh
      - run: ./jfrog rt c artifactory --url=https://connyun.jfrog.io/connyun/ --apikey=${ARTIFACTORY_NPM_API_KEY}
      - run: ./jfrog rt bag ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BUILD_NUM}
      - run: ./jfrog rt bce ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BUILD_NUM}
      - run: ./jfrog rt npmp npm --build-name=${CIRCLE_PROJECT_REPONAME} --build-number=${CIRCLE_BUILD_NUM}
      - run: ./jfrog rt bp ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: connyun
          filters:
            tags:
              only: /.*/
      - tags:
          context: connyun
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
